### ISSUE TITLE
[Bug] Writing in demo disables intellisense

### ISSUE THREAD

**Issue by sskieller** [huntercfreeman/Blazor.Text.Editor#31]
Hello, when editing in your demo I end up with a disabled intellisense: 
![image](https://user-images.githubusercontent.com/11709063/207095168-3c242f23-e1af-4ed1-b079-1b6ad752c28a.png)

**Comment by huntercfreeman** [comment]
A large amount of change has occurred since the opening of this issue. In addition, I am unable to reproduce this. So, for now I will close this.

Please let me know this issue still exists for you.
