### ISSUE TITLE
[Bug] Lagging when scrolling through many lines 

### ISSUE THREAD

**Issue by sskieller** [huntercfreeman/Blazor.Text.Editor#32]
The editor is lagging when scrolling through many lines as seen below:
![Animation](https://user-images.githubusercontent.com/11709063/207097299-06d0ea8e-ec78-4385-ab41-e4d0fc3f1d41.gif)

**Comment by huntercfreeman** [comment]
I believe this issue is fixed. Some of the cancellation token logic for re-rendering has been changed.

Please let me know if this is still occurring.
