### ISSUE TITLE
Text editor throws Fluxor Exception: DisposableCallback

### ISSUE THREAD

**Issue by ummerland** [huntercfreeman/Blazor.Text.Editor#71]
Hi
I like your text editor very much, nice work.

From time to time however, it throws this Fluxor Exception:

```
Exception Info: System.InvalidOperationException: DisposableCallback with Id ""StateSubscriber.Subscribe" (created in "C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\StateSubscriber.cs" on line 50)" was not disposed. See https://github.com/mrpmorris/Fluxor/tree/master/Docs/disposable-callback-not-disposed.md for more details
   at Fluxor.DisposableCallback.Finalize() in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\DisposableCallback.cs:line 75
```

Looking at the provided link https://github.com/mrpmorris/Fluxor/tree/master/Docs/disposable-callback-not-disposed.md reveals that something seems to not beeing disposed correctly.

Unfortunately i am unable to build the Blazor.Text.Editor from your main branch. Probably its just a small issue.

Thanks for your help.

**Comment by huntercfreeman** [comment]
Hi, I'm happy to hear you like the Text Editor.

I just now uploaded v7.1.0 of the text editor to nuget, this version includes a fix for what you describe.
